-- 
-- SELECT 
-- job_title_short AS title,
-- job_location AS location,
-- job_posted_date::DATE AS date       --it removes dates times stamps
-- FROM job_postings_fact
-- 
-- SELECT 
-- job_title_short AS title,
-- job_location AS location,
-- job_posted_date AT TIME ZONE 'UTC' AT TIME ZONE 'EST'  AS date_time    
-- FROM job_postings_fact
-- LIMIT 5;
-- SELECT 
-- job_title_short AS title,
-- job_location AS location,
-- job_posted_date AT TIME ZONE 'UTC' AT TIME ZONE 'EST'  AS date_time  ,  
-- EXTRACT (MONTH FROM job_posted_date) AS DATE_MONTH,
-- EXTRACT (YEAR FROM job_posted_date) AS DATE_year
-- FROM job_postings_fact
-- LIMIT 5;
-- SELECT COUNT(job_id) AS JOB_COUNT,
-- EXTRACT(MONTH FROM job_posted_date) AS months
-- FROM job_postings_fact
-- WHERE job_title_short = 'Data Analyst'
-- GROUP BY MONTH
-- ORDER BY JOB_COUNT DESC;